name: Frontend CI pipline

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
jobs:
 test-code:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout JS/main.js's code
        run: node --check JS/main.js
      - name: Checkout JS/time.js's code
        run: node --check JS/time.js